name: tailscale ssh
on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - run: sleep infinity
